import "./globals.css";
import type { Metadata } from "next";
// Components
import {
  Header,
  Notification,
  Footer,
  AuthProvider,
  QueryProvider,
} from "@/components";

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <AuthProvider>
          <QueryProvider>
            <Notification />
            <Header />
            <main>{children}</main>
            <Footer />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
